name: Deploy PowerShell Functions

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  provision-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      function_app_name: ${{ steps.tf.outputs.function_app_name }}

    env:
      PROJECT_NAME: powershell-functions
      ENV_NAME: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'staging' && 'staging' || 'dev' }}

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3
          terraform_wrapper: false

      - name: Set state key
        run: echo "STATE_KEY=tfstate/${PROJECT_NAME}/${ENV_NAME}.tfstate" >> $GITHUB_ENV

      - name: Init Terraform
        working-directory: ./terraform
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform init

      - name: Apply Terraform (auto-approve)
        working-directory: ./terraform
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve

      - name: Export Terraform output
        working-directory: ./terraform
        id: tf
        run: echo "function_app_name=$(terraform output -raw function_app_name)" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    needs: provision-infra 

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        shell: pwsh
        run: Install-Module -Name powershell-yaml -Force -Scope CurrentUser

      - name: Generate Azure Functions layout
        shell: pwsh
        run: ./builder/build.ps1

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: 'Run the Azure Functions action'
        uses: azure/functions-action@v1
        id: deploy-to-function-app
        with:
          app-name: ${{ needs.provision-infra.outputs.function_app_name }}
          package: ./dist
