name: Deploy PowerShell Functions

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        shell: pwsh
        run: Install-Module -Name powershell-yaml -Force -Scope CurrentUser

      - name: Generate Azure Functions layout
        shell: pwsh
        run: ./builder/build.ps1

      - name: Upload dist/ content as artifact
        uses: actions/upload-artifact@v4
        with:
          name: functions
          path: dist/

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Init Terraform
        run: terraform init

      - name: Apply Terraform (auto-approve)
        run: terraform apply -auto-approve
      # - name: Deploy to Azure
      #   uses: Azure/functions-action@v1
      #   with:
      #     app-name: <TON_APP_NAME>
      #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
      #     package: ./build
