name: Deploy PowerShell Functions

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  provision-infra:
    runs-on: ubuntu-latest
    outputs:
      function_app_name: ${{ steps.tf-output.outputs.function_app_name }}

    permissions:
      id-token: write
      contents: read

    env:
      PROJECT_NAME: powershell-functions
      ENV_NAME: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'staging' && 'staging' || 'dev' }}

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Set state key
        run: echo "STATE_KEY=tfstate/${PROJECT_NAME}/${ENV_NAME}.tfstate" >> $GITHUB_ENV

      - name: Init Terraform
        working-directory: ./terraform
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform init

      - name: Apply Terraform (auto-approve)
        working-directory: ./terraform
        id: tf-output
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          terraform apply -auto-approve
          terraform output -raw function_app_name

          $OUT=terraform output -raw function_app_name
          echo "function_app_name=$OUT" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: provision-infra 
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        shell: pwsh
        run: Install-Module -Name powershell-yaml -Force -Scope CurrentUser

      - name: Generate Azure Functions layout
        shell: pwsh
        run: ./builder/build.ps1

      - name: Zip the Function App
        run: |
          cd dist
          zip -r ../function.zip .

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ needs.provision-infra.outputs.function_app_name }}
          package: ./function.zip

      - name: Upload dist/ content as artifact
        uses: actions/upload-artifact@v4
        with:
          name: functions
          path: ./functions.zip
